version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: tusch-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tusch_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

 
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: tusch-api
    depends_on:
      - db
    ports:
      - "3310:3310"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/tusch_db
    command: node dist/main.js

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: tusch-web
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3310
    command: pnpm start

volumes:
  db_data:
